[build]
    publish = "site/"
    command = "rm -rf site/assets/ && mkdir site/assets/ && rsync -rv node_modules/reveal.js/dist/ site/assets && mkdir site/assets/plugin && rsync -rv node_modules/reveal.js/plugin/ site/assets/plugin"
